version: '3'

services:
  rgr-scrapping-api:
    container_name: rgr-scrapping-api
    image: rguasch/php
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9003:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app:delegated
    command: symfony serve --port=8040
    depends_on:
      - rgr-scrapping-database
    networks:
      - rgr_scrapping

  rgr-scrapping-database:
    image: postgres:14.3
    container_name: rgr-scrapping-database
    environment:
      POSTGRES_DB: scrapping
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data:rw
    networks:
      - rgr_scrapping

volumes:
  database-data:


#Docker Networks
networks:
  rgr_scrapping:
    driver: bridge
